version: 2

references:
  fast_checkout: &fast_checkout
    attach_workspace:
      at: '.'

jobs:
  persist_checkout:
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
          keys:
            - repo-source-{{ .Branch }}-{{ .Revision }}
            - repo-source-{{ .Branch }}-
            - repo-source-
      - checkout
      - run: git gc # Built-in checkout disables garbage collection - https://circleci.com/docs/2.0/caching/
      - save_cache:
          key: repo-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'
      - run: echo `ls`
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  build_workspace_a:
    docker:
      - image: circleci/node:10
    steps:
      - *fast_checkout
      - run: env
      - run: deploy/maybe-build.sh workspace-a

  build_workspace_b:
    docker:
      - image: circleci/node:10
    steps:
      - *fast_checkout
      - run: env
      - run: deploy/maybe-build.sh workspace-b

  build_workspace_c:
    docker:
      - image: circleci/node:10
    steps:
      - *fast_checkout
      - run: env
      - run: deploy/maybe-build.sh workspace-c

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - persist_checkout
      - build_workspace_a:
          requires:
            - persist_checkout
      - build_workspace_b:
          requires:
            - persist_checkout
      - build_workspace_c:
          requires:
            - persist_checkout
