version: 2

references:
  fast-checkout: &fast-checkout
    attach_workspace:
      at: '.'

jobs:
  persist_checkout:
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
          keys:
            - repo-source-{{ .Branch }}-{{ .Revision }}
            - repo-source-{{ .Branch }}-
            - repo-source-
      - checkout
      - save_cache:
          key: repo-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'
      - run: echo `ls`
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  build:
    docker:
      - image: circleci/node:10
    steps:
      - *fast-checkout
      - echo `ls .git`

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - persist_checkout
      - build:
          requires:
            - persist_checkout
