version: 2

references:
  fast-checkout: &fast-checkout
    attach_workspace:
      at: /root

jobs:
  persist_checkout:
    docker:
      - image: node:10-alpine
    steps:
      - restore_cache:
          keys:
            - repo-source-{{ .Branch }}-{{ .Revision }}
            - repo-source-{{ .Branch }}-
            - repo-source-
      - checkout
      - save_cache:
          key: repo-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'

      - persist_to_workspace:
          root: /root
          paths:
            - monorepo

  build:
    docker:
      - image: node:10-alpine
    *fast-checkout
    steps:
      - echo `ls .git`

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - persist_checkout
      - build:
          requires:
            - persist_checkout
