version: 2

jobs:
  persisted_checkout:
    docker:
      - image: circleci/node:10
    steps:
      - restore_cache:
          keys:
            - repo-source-{{ .Branch }}-{{ .Revision }}
            - repo-source-{{ .Branch }}-
            - repo-source-
      - checkout
      - save_cache:
          key: repo-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'

  build:
    docker:
      - image: circleci/node:10
    steps:
      - *fast-checkout
      - echo `ls .git`

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - persisted_checkout
      - build:
          requires:
            - persist_checkout
